"""Generate golden DXF files for regression testing.

Run with: python -m tests.generate_golden
Outputs to tests/golden/

The .snap snapshot fixtures are NOT regenerated by that. See rebaseline_snapshots.
"""

import argparse
import difflib
import os
import sys
from pathlib import Path

import ezdxf

GOLDEN_DIR = Path(__file__).parent / "golden"

#: Both gates must be open before a .snap fixture is overwritten.
REBASELINE_ENV = "AUTOCAD_MCP_REBASELINE"
REBASELINE_FLAG = "--rebaseline-snapshots"


def generate_basic_shapes():
    """Golden file: basic geometric shapes on multiple layers."""
    doc = ezdxf.new("R2013")
    msp = doc.modelspace()

    # Create layers
    doc.layers.add("BORDER", color=7, linetype="Continuous")
    doc.layers.add("SHAPES", color=3, linetype="Continuous")
    doc.layers.add("ANNOTATION", color=4, linetype="Continuous")

    # Border rectangle
    msp.add_lwpolyline(
        [(0, 0), (200, 0), (200, 100), (0, 100)],
        close=True,
        dxfattribs={"layer": "BORDER"},
    )

    # Shapes
    msp.add_line((10, 10), (50, 50), dxfattribs={"layer": "SHAPES"})
    msp.add_circle((100, 50), 30, dxfattribs={"layer": "SHAPES"})
    msp.add_arc((150, 50), 20, 0, 180, dxfattribs={"layer": "SHAPES"})
    msp.add_lwpolyline(
        [(60, 20), (80, 20), (80, 40), (60, 40)],
        close=True,
        dxfattribs={"layer": "SHAPES"},
    )

    # Annotation
    msp.add_text("BASIC SHAPES", dxfattribs={
        "insert": (10, 90), "height": 5, "layer": "ANNOTATION",
    })

    doc.saveas(str(GOLDEN_DIR / "basic_shapes.dxf"))
    print(f"Generated: {GOLDEN_DIR / 'basic_shapes.dxf'}")


def generate_pid_example():
    """Golden file: simple P&ID layout."""
    doc = ezdxf.new("R2013")
    msp = doc.modelspace()

    # P&ID layers
    layers = [
        ("PID-EQUIPMENT", 6),
        ("PID-PROCESS-PIPING", 4),
        ("PID-ANNOTATION", 7),
        ("PID-VALVES", 2),
    ]
    for name, color in layers:
        doc.layers.add(name, color=color, linetype="Continuous")

    # Equipment: simplified tank (rectangle)
    msp.add_lwpolyline(
        [(20, 20), (60, 20), (60, 60), (20, 60)],
        close=True,
        dxfattribs={"layer": "PID-EQUIPMENT"},
    )
    # Equipment: simplified pump (circle)
    msp.add_circle((120, 40), 15, dxfattribs={"layer": "PID-EQUIPMENT"})

    # Process piping with orthogonal routing
    msp.add_lwpolyline(
        [(60, 40), (90, 40), (90, 40), (105, 40)],
        dxfattribs={"layer": "PID-PROCESS-PIPING"},
    )

    # Valve symbol (simplified diamond)
    msp.add_lwpolyline(
        [(87, 40), (90, 45), (93, 40), (90, 35)],
        close=True,
        dxfattribs={"layer": "PID-VALVES"},
    )

    # Tags
    msp.add_text("TK-101", dxfattribs={
        "insert": (25, 62), "height": 3, "layer": "PID-ANNOTATION",
    })
    msp.add_text("P-101", dxfattribs={
        "insert": (112, 58), "height": 3, "layer": "PID-ANNOTATION",
    })
    msp.add_text("V-101", dxfattribs={
        "insert": (85, 48), "height": 2, "layer": "PID-ANNOTATION",
    })

    doc.saveas(str(GOLDEN_DIR / "pid_example.dxf"))
    print(f"Generated: {GOLDEN_DIR / 'pid_example.dxf'}")


#: The drawings that carry a committed .snap fixture.
SNAPSHOT_SOURCES = ("basic_shapes", "pid_example")


def snapshot_path(stem: str) -> Path:
    return GOLDEN_DIR / f"{stem}.snap"


def current_snapshot(stem: str) -> str:
    """What the probes make of the golden DXF right now."""
    from autocad_mcp.probe_dxf import snapshot_file

    return snapshot_file(GOLDEN_DIR / f"{stem}.dxf")


class RebaselineRefused(RuntimeError):
    """Raised when a .snap overwrite was attempted without both gates open."""


def rebaseline_snapshots(confirmed: bool = False, env=None) -> list[str]:
    """Overwrite the committed .snap fixtures. Deliberately hard to reach.

    A golden file only means something if changing it is a decision. The
    failure mode this guards against is specific and unglamorous: a snapshot
    test goes red, and the cheapest way to make it green is to regenerate the
    fixture — which converts a caught regression into a committed one, and
    leaves a diff that looks like intent.

    So there are two independent gates, and neither is something you trip over:
    the REBASELINE_FLAG argument, and AUTOCAD_MCP_REBASELINE=1 in the
    environment. The test failure message names neither. Rebaselining is
    something a person decides to do after reading the diff, and the diff is
    printed here before anything is written.
    """
    env = os.environ if env is None else env
    if not confirmed:
        raise RebaselineRefused(
            f"Refusing to rewrite .snap fixtures: pass {REBASELINE_FLAG}."
        )
    if env.get(REBASELINE_ENV) != "1":
        raise RebaselineRefused(
            f"Refusing to rewrite .snap fixtures: {REBASELINE_ENV}=1 is not set. "
            "Read the diff in the test failure first — if the change was not "
            "intended, the fixture is right and the code is wrong."
        )

    written = []
    for stem in SNAPSHOT_SOURCES:
        path = snapshot_path(stem)
        new = current_snapshot(stem)
        old = path.read_text(encoding="utf-8") if path.exists() else ""
        if old == new:
            print(f"Unchanged: {path.name}")
            continue
        # Print what is about to be lost, before losing it.
        print(f"\n--- rebaselining {path.name} ---")
        sys.stdout.writelines(
            difflib.unified_diff(
                old.splitlines(keepends=True), new.splitlines(keepends=True),
                fromfile=f"{path.name} (committed)", tofile=f"{path.name} (new)",
            )
        )
        path.write_text(new, encoding="utf-8")
        written.append(path.name)
    return written


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        REBASELINE_FLAG,
        dest="rebaseline",
        action="store_true",
        help=f"Overwrite tests/golden/*.snap. Also requires {REBASELINE_ENV}=1.",
    )
    args = parser.parse_args(argv)

    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)

    if args.rebaseline:
        try:
            written = rebaseline_snapshots(confirmed=True)
        except RebaselineRefused as exc:
            print(exc, file=sys.stderr)
            return 2
        print(f"\nRebaselined: {', '.join(written) if written else 'nothing'}")
        return 0

    generate_basic_shapes()
    generate_pid_example()
    print("Done. Snapshots were not touched — see rebaseline_snapshots.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
